
Downloading training data


In [ ]:
!wget -nc https://raw.githubusercontent.com/lazyprogrammer/machine_learning_examples/master/hmm_class/edgar_allan_poe.txt

--2025-12-20 17:41:10--  https://raw.githubusercontent.com/lazyprogrammer/machine_learning_examples/master/hmm_class/edgar_allan_poe.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 26622 (26K) [text/plain]
Saving to: ‘edgar_allan_poe.txt’

edgar_allan_poe.txt 100%[===================>]  26.00K  --.-KB/s    in 0.002s  

2025-12-20 17:41:10 (11.8 MB/s) - ‘edgar_allan_poe.txt’ saved [26622/26622]



In [ ]:
!wget -nc https://raw.githubusercontent.com/lazyprogrammer/machine_learning_examples/master/hmm_class/robert_frost.txt

--2025-12-20 17:41:34--  https://raw.githubusercontent.com/lazyprogrammer/machine_learning_examples/master/hmm_class/robert_frost.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 56286 (55K) [text/plain]
Saving to: ‘robert_frost.txt’

robert_frost.txt    100%[===================>]  54.97K  --.-KB/s    in 0.01s   

2025-12-20 17:41:34 (4.09 MB/s) - ‘robert_frost.txt’ saved [56286/56286]



importing need libraries

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import string
from sklearn.model_selection import train_test_split

importing the two peoms

In [ ]:
import_files = ["edgar_allan_poe.txt", "robert_frost.txt"]

seeing what it contains

In [ ]:
!head edgar_allan_poe.txt

LO! Death hath rear'd himself a throne
In a strange city, all alone,
Far down within the dim west
Where the good, and the bad, and the worst, and the best,
Have gone to their eternal rest.
 
There shrines, and palaces, and towers
Are not like any thing of ours
Oh no! O no! ours never loom
To heaven with that ungodly gloom!


In [ ]:
!head robert_frost.txt

Two roads diverged in a yellow wood,
And sorry I could not travel both
And be one traveler, long I stood
And looked down one as far as I could
To where it bent in the undergrowth; 

Then took the other, as just as fair,
And having perhaps the better claim
Because it was grassy and wanted wear,
Though as for that the passing there


Labelling train data as 0 and 1 for each poet

In [10]:
input_texts = []
labels = []
for label, f in enumerate(import_files):
  print(f"{f} corresponds to label {label}")
  for line in open(f):
    line = line.rstrip().lower()
    if line:
      line = line.translate(str.maketrans('', '', string.punctuation))
      input_texts.append(line)
      labels.append(label)

edgar_allan_poe.txt corresponds to label 0
robert_frost.txt corresponds to label 1


Taking out train data and test data

In [11]:
train_text, test_text, Ytrain, Ytest = train_test_split(input_texts, labels)

In [12]:
len(Ytrain), len(Ytest)

(1615, 539)

In [13]:
train_text[:5], test_text[:5]

(['but why when shes well off is it the neighbours',
  'you spoke of johns not being safe to stay with',
  'as for the woods excitement over you',
  'the sacred sun of all who weeping bless thee',
  'of what in other worlds shall be  and given'],
 ['and begin over   there shed better stop',
  'i made him gather me wet snow berries',
  'how daring an ambition yet how deep',
  'spirits moving musically',
  'a bill'])

Setting index as 1 and storing unkown words in 0 index

In [14]:
idx = 1
word2idx = {"<unk>": 0}

In [15]:
for text in train_text:
  token = text.split()
  for word in token:
    if word not in word2idx:
      word2idx[word] = idx
      idx += 1

In [16]:
word2idx

{'<unk>': 0,
 'but': 1,
 'why': 2,
 'when': 3,
 'shes': 4,
 'well': 5,
 'off': 6,
 'is': 7,
 'it': 8,
 'the': 9,
 'neighbours': 10,
 'you': 11,
 'spoke': 12,
 'of': 13,
 'johns': 14,
 'not': 15,
 'being': 16,
 'safe': 17,
 'to': 18,
 'stay': 19,
 'with': 20,
 'as': 21,
 'for': 22,
 'woods': 23,
 'excitement': 24,
 'over': 25,
 'sacred': 26,
 'sun': 27,
 'all': 28,
 'who': 29,
 'weeping': 30,
 'bless': 31,
 'thee': 32,
 'what': 33,
 'in': 34,
 'other': 35,
 'worlds': 36,
 'shall': 37,
 'be': 38,
 'and': 39,
 'given': 40,
 'a': 41,
 'world': 42,
 'sweets': 43,
 'sours': 44,
 'should': 45,
 'say': 46,
 'our': 47,
 'stock': 48,
 'was': 49,
 'petered': 50,
 'out': 51,
 'isnt': 52,
 'grandsir': 53,
 'stark': 54,
 'its': 55,
 'granny': 56,
 'here': 57,
 'are': 58,
 'your': 59,
 'waters': 60,
 'watering': 61,
 'place': 62,
 'put': 63,
 'sign': 64,
 'up': 65,
 'closed': 66,
 'me': 67,
 'now': 68,
 'night': 69,
 'senescent': 70,
 'i': 71,
 'may': 72,
 'mad': 73,
 'arthur': 74,
 'amy': 75,
 'marr

In [17]:
len(word2idx)

2510

converting the words in word2idx into numbers

In [18]:
train_text_int = []
test_text_int = []

for text in train_text:
  tokens = text.split()
  line_as_int = [word2idx[token] for token in tokens]
  train_text_int.append(line_as_int)

for text in test_text:
  tokens = text.split()
  line_as_int = [word2idx.get(token, 0) for token in tokens]
  test_text_int.append(line_as_int)

In [19]:
train_text_int[100:105]

[[248, 7, 47, 385, 386, 41, 387, 388],
 [13, 389, 390, 107, 391],
 [115, 392, 107, 393, 13, 9, 394],
 [57, 239, 395, 389, 396, 397],
 [398, 399, 400, 22, 115, 401, 126]]

using Bayes classification model to compute A and pi for markov model

In [20]:
V = len(word2idx)

A0 = np.ones((V, V))
pi0 = np.ones(V)

A1 = np.ones((V, V))
pi1 = np.ones(V)


def compute_counts(text_as_int, A, pi):
  for tokens in text_as_int:
    last_idx = None
    for idx in tokens:
      if last_idx is None:
        pi[idx] += 1
      else:
        A[last_idx, idx] += 1

      last_idx = idx

  return A, pi

In [21]:
compute_counts([t for t, y in zip(train_text_int, Ytrain) if y == 0], A0, pi0)

(array([[1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        ...,
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.]]),
 array([1., 9., 2., ..., 1., 1., 1.]))

In [22]:
compute_counts([t for t, y in zip(train_text_int, Ytrain) if y == 1], A1, pi1)

(array([[1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 3., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        ...,
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.]]),
 array([ 1., 43.,  3., ...,  1.,  1.,  1.]))

In [23]:
A0 /= A0.sum(axis=1, keepdims=True)
pi0 /= pi0.sum()

A1 /= A1.sum(axis=1, keepdims=True)
pi1 /= pi1.sum()

In [24]:
logA0 = np.log(A0)
logpi0 = np.log(pi0)

logA1 = np.log(A1)
logpi1 = np.log(pi1)

In [25]:
count0 = sum(y == 0 for y in Ytrain)
count1 = sum(y == 1 for y in Ytrain)
total = len(Ytrain)
p0 = count0 / total
p1 = count1 / total
logp0 = np.log(p0)
logp1 = np.log(p1)
p0, p1

(0.33622291021671824, 0.6637770897832818)

Creating the classifier model

In [26]:
class Classifier:
  def __init__(self, logAs, logpis, logpriors):
    self.logAs = logAs
    self.logpis = logpis
    self.logpriors = logpriors
    self.K = len(logpriors)

  def _compute_log_likelihood(self, input_, class_):
    logA = self.logAs[class_]
    logpi = self.logpis[class_]

    last_idx = None
    logprob = 0
    for idx in input_:
      if last_idx is None:
        logprob += logpi[idx]
      else:
        logprob += logA[last_idx, idx]
      last_idx = idx

    return logprob

  def predict(self, inputs):
    predictions = np.zeros(len(inputs))
    for i, input_ in enumerate(inputs):
      posteriors = [self._compute_log_likelihood(input_, c) + self.logpriors[c] \
                     for c in range(self.K)]
      pred = np.argmax(posteriors)
      predictions[i] = pred
    return predictions

In [27]:
clf = Classifier([logA0, logA1], [logpi0, logpi1], [logp0, logp1])

In [28]:
Ptrain = clf.predict(train_text_int)
print(f"Train acc: {np.mean(Ptrain == Ytrain)}")

Train acc: 0.9962848297213622


In [29]:
Ptest = clf.predict(test_text_int)
print(f"Test acc: {np.mean(Ptest == Ytest)}")

Test acc: 0.8404452690166976


Using confusion metrix

In [30]:
from sklearn.metrics import confusion_matrix, f1_score

In [31]:
cm = confusion_matrix(Ytrain, Ptrain)
cm

array([[ 537,    6],
       [   0, 1072]])

In [32]:
cm_test = confusion_matrix(Ytest, Ptest)
cm_test

array([[ 98,  77],
       [  9, 355]])

In [34]:
f1_score(Ytrain, Ptrain)

0.9972093023255814

In [35]:
f1_score(Ytest, Ptest)

0.8919597989949749